### ISSUE TITLE
com.sun.activation.registries.LogSupport is not public

### ISSUE THREAD

**Issue by vojkny** [eclipse-ee4j/angus-activation#26]
**Describe the bug**
In comparison to preceding `com.sun.activation` implementation the class `LogSupport` is NOT PUBLIC.

This unfortunately fails when sending emails:

```
java.lang.IllegalAccessError: failed to access class com.sun.activation.registries.LogSupport from class jakarta.activation.MailcapCommandMap (com.sun.activation.registries.LogSupport and jakarta.activation.MailcapCommandMap are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @6bca7e0d)
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:149) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:55) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:127) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:589) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1580) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1177) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:510) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1538) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2265) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2225) ~[jakarta.mail-api-2.1.0.jar:?]
	at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1904) ~[jakarta.mail-api-2.1.0.jar:?]
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1332) ~[angus-mail-1.0.0.jar:?]
```

When using the previous `com.sun.activation` implementation, it works correctly.

Some users suggest avoiding usage of `angus` implementation to prevent this:

https://stackoverflow.com/questions/73034101/resolved-spring-boot-starter-mail-failed-to-access-class-com-sun-activation/75050338#75050338

**To Reproduce**
1. Use legacy com.sun.activation package to send email - it works.
2. Change the implementation for angus and it fails.

**Comment by lukasj** [comment]
```
	at jakarta.activation.DataHandler.writeTo(DataHandler.java:289) ~[jakarta.activation-2.0.0.jar:2.0.0]
	at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316) ~[jakarta.mail-api-2.1.0.jar:?]
```

Angus implements Activation 2.1/Mail 2.1, what is being used here is Activation 2.0 and Mail 2.1 which is untested/unsupported combination. Feel free to reopen if it happens with activation-api 2.1.0 and attach sample project to reproduce this. Thanks.

**Comment by vojkny** [comment]
Thanks, this was caused by hibernate-jakarta which has the legacy version in dependencies 🤦
